name: image_sharing_application
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  flutter_bloc: ^8.1.3
  equatable: ^2.0.5
  http: ^1.1.0
  intl: ^0.18.1
  shared_preferences: ^2.2.2
  url_launcher: ^6.2.1
  path_provider: ^2.1.1
  anim_search_bar: ^2.0.3
  flutter_staggered_grid_view: ^0.7.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  bloc_test: ^9.1.4
  mockito: ^5.4.2
  build_runner: ^2.4.6

flutter:
  uses-material-design: true
  
# Platform-specific configuration  
flutter_platform_support:
  platforms:
    - ios
    - android
    - web
    - macos
    # Excluding Linux to avoid path_provider_linux dependency issues 