// Mocks generated by Mockito 5.4.5 from annotations
// in image_sharing_application/test/bloc/favorites_bloc_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i7;

import 'package:image_sharing_application/api/imgur_api_client.dart' as _i2;
import 'package:image_sharing_application/models/imgur_gallery_item.dart'
    as _i5;
import 'package:image_sharing_application/models/imgur_image.dart' as _i4;
import 'package:image_sharing_application/repositories/imgur_repository.dart'
    as _i6;
import 'package:mockito/mockito.dart' as _i1;
import 'package:shared_preferences/shared_preferences.dart' as _i3;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeImgurApiClient_0 extends _i1.SmartFake
    implements _i2.ImgurApiClient {
  _FakeImgurApiClient_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeSharedPreferences_1 extends _i1.SmartFake
    implements _i3.SharedPreferences {
  _FakeSharedPreferences_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeImgurImage_2 extends _i1.SmartFake implements _i4.ImgurImage {
  _FakeImgurImage_2(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeImgurGalleryItem_3 extends _i1.SmartFake
    implements _i5.ImgurGalleryItem {
  _FakeImgurGalleryItem_3(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [ImgurRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockImgurRepository extends _i1.Mock implements _i6.ImgurRepository {
  MockImgurRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.ImgurApiClient get apiClient =>
      (super.noSuchMethod(
            Invocation.getter(#apiClient),
            returnValue: _FakeImgurApiClient_0(
              this,
              Invocation.getter(#apiClient),
            ),
          )
          as _i2.ImgurApiClient);

  @override
  _i3.SharedPreferences get sharedPreferences =>
      (super.noSuchMethod(
            Invocation.getter(#sharedPreferences),
            returnValue: _FakeSharedPreferences_1(
              this,
              Invocation.getter(#sharedPreferences),
            ),
          )
          as _i3.SharedPreferences);

  @override
  _i7.Future<List<_i5.ImgurGalleryItem>> getGalleryImages({
    String? section = 'hot',
    String? sort = 'viral',
    String? window = 'day',
    int? page = 0,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#getGalleryImages, [], {
              #section: section,
              #sort: sort,
              #window: window,
              #page: page,
            }),
            returnValue: _i7.Future<List<_i5.ImgurGalleryItem>>.value(
              <_i5.ImgurGalleryItem>[],
            ),
          )
          as _i7.Future<List<_i5.ImgurGalleryItem>>);

  @override
  _i7.Future<List<_i5.ImgurGalleryItem>> searchGalleryImages({
    required String? query,
    String? sort = 'viral',
    String? window = 'all',
    int? page = 0,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#searchGalleryImages, [], {
              #query: query,
              #sort: sort,
              #window: window,
              #page: page,
            }),
            returnValue: _i7.Future<List<_i5.ImgurGalleryItem>>.value(
              <_i5.ImgurGalleryItem>[],
            ),
          )
          as _i7.Future<List<_i5.ImgurGalleryItem>>);

  @override
  _i7.Future<_i4.ImgurImage> getImageDetails(String? imageId) =>
      (super.noSuchMethod(
            Invocation.method(#getImageDetails, [imageId]),
            returnValue: _i7.Future<_i4.ImgurImage>.value(
              _FakeImgurImage_2(
                this,
                Invocation.method(#getImageDetails, [imageId]),
              ),
            ),
          )
          as _i7.Future<_i4.ImgurImage>);

  @override
  _i7.Future<_i5.ImgurGalleryItem> getAlbumDetails(String? albumId) =>
      (super.noSuchMethod(
            Invocation.method(#getAlbumDetails, [albumId]),
            returnValue: _i7.Future<_i5.ImgurGalleryItem>.value(
              _FakeImgurGalleryItem_3(
                this,
                Invocation.method(#getAlbumDetails, [albumId]),
              ),
            ),
          )
          as _i7.Future<_i5.ImgurGalleryItem>);

  @override
  _i7.Future<void> addToFavorites(_i4.ImgurImage? image) =>
      (super.noSuchMethod(
            Invocation.method(#addToFavorites, [image]),
            returnValue: _i7.Future<void>.value(),
            returnValueForMissingStub: _i7.Future<void>.value(),
          )
          as _i7.Future<void>);

  @override
  _i7.Future<void> removeFromFavorites(String? imageId) =>
      (super.noSuchMethod(
            Invocation.method(#removeFromFavorites, [imageId]),
            returnValue: _i7.Future<void>.value(),
            returnValueForMissingStub: _i7.Future<void>.value(),
          )
          as _i7.Future<void>);

  @override
  List<_i4.ImgurImage> getFavoriteImages() =>
      (super.noSuchMethod(
            Invocation.method(#getFavoriteImages, []),
            returnValue: <_i4.ImgurImage>[],
          )
          as List<_i4.ImgurImage>);

  @override
  _i7.Future<void> addRecentSearch(String? searchTerm) =>
      (super.noSuchMethod(
            Invocation.method(#addRecentSearch, [searchTerm]),
            returnValue: _i7.Future<void>.value(),
            returnValueForMissingStub: _i7.Future<void>.value(),
          )
          as _i7.Future<void>);

  @override
  _i7.Future<void> removeRecentSearch(String? searchTerm) =>
      (super.noSuchMethod(
            Invocation.method(#removeRecentSearch, [searchTerm]),
            returnValue: _i7.Future<void>.value(),
            returnValueForMissingStub: _i7.Future<void>.value(),
          )
          as _i7.Future<void>);

  @override
  List<String> getRecentSearches() =>
      (super.noSuchMethod(
            Invocation.method(#getRecentSearches, []),
            returnValue: <String>[],
          )
          as List<String>);

  @override
  _i7.Future<void> clearRecentSearches() =>
      (super.noSuchMethod(
            Invocation.method(#clearRecentSearches, []),
            returnValue: _i7.Future<void>.value(),
            returnValueForMissingStub: _i7.Future<void>.value(),
          )
          as _i7.Future<void>);
}
